image: "docker.mjdsystems.ca/docker/rust-builder"

stages:
  - build

test:cargo:debug:
  stage:
    build
  script:
  - rustc --version && cargo --version
  - cargo build --verbose
  - cargo clippy -- --deny warnings
  - cargo test --verbose

test:cargo:release:
  stage:
    build
  script:
  - rustc --version && cargo --version
  - cargo build --release --verbose
  - cargo clippy --release -- --deny warnings
  - cargo test --release --verbose

test:rustfmt:
  stage:
    build
  script:
  - cargo fmt -- --check
